version: "3.8"

services:
  db:
    image: postgres:14-bullseye
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5442:5432
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
      - dbt-store:/var/lib/postgresql/data

volumes:
  dbt-store: